project:
  type: book
  output-dir: docs

book:
  title: "Introduction to data analysis and visualization with R"
  author: "György Barabás & Isak Hietala"
  chapters:
    - index.qmd
    - part: "Part I: Processing and visualizing data with R"
      chapters:
      - 1_Intro_R_RStudio.qmd
      - R_programming_basics.qmd
      - Functions.qmd
      - Data_reading.qmd
      - Basic_data_wrangling.qmd
      - Summaries_normalization.qmd
      - Creating_figures.qmd
      - Further_plotting_options.qmd
      - Joining_data.qmd
    - part: "Part II: Introductory statistics"
      chapters:
      - Intro_statistics.qmd
    - part: "Part III: Advanced statistics"
      chapters:
      - Intro_adv_statistics.qmd
      - Linear_regression.qmd
      - Anova.qmd
      - Anova_two_way.qmd
      - Nonlinear_regression.qmd
      - Intro_map.qmd
      - Multiple_analysis.qmd
    - part: "References"
      chapters:
      - References.qmd

bibliography: biblio.bib

format:
  html:
    theme: cosmo
    toc-depth: 3
    number-depth: 3
